version: '3'

services:
  go-api:
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/golang-docker
    depends_on:
      - database
    container_name: go-api
    environment:
      - 'DB_PORT=3306'
      - 'DB_HOST=database'

  database:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: rafael
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test
    container_name: golang-docker-db
    ports:
      - 3306:3306
    volumes:
      - golang-docker-data:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - 5003:80
    environment:
      - 'PMA_HOST=database'
      - 'PMA_PORT=3306'
    container_name: golang-docker-pma


# persisted storage
volumes:
  golang-docker-data: